<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Downup_model extends CI_Model
{

    public $table = 'downup';
    public $id = 'no';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('no,nama_file,id_perusahaan');
        $this->datatables->from('downup');
        //add this line for join
        //$this->datatables->join('table2', 'downup.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('assets/uploads/$2'),'Download')." | ".anchor(site_url('downup/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no,nama_file');
        return $this->datatables->generate();
    }

    function json2() {
        $this->datatables->select('no,nama_file,id_perusahaan');
        $this->datatables->from('downup');
        //add this line for join
        //$this->datatables->join('table2', 'downup.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('assets/uploads/$2'),'Download'), 'no,nama_file');
        return $this->datatables->generate();
    }

    function json3($id) {
        $this->datatables->select('no,nama_file,id_perusahaan');
        $this->datatables->from('downup');        
        $this->datatables->where('id_perusahaan', $id);
        //add this line for join
        //$this->datatables->join('table2', 'downup.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('downup/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no,nama_file');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no', $q);
	$this->db->or_like('nama_file', $q);
	$this->db->or_like('id_perusahaan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no', $q);
	$this->db->or_like('nama_file', $q);
	$this->db->or_like('id_perusahaan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Downup_model.php */
/* Location: ./application/models/Downup_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-08-26 11:17:02 */
/* http://harviacode.com */