<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_model extends CI_Model
{

    public $table = 'nilai';
    public $id = 'id_perusahaan';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables,
    function json($jenis_lelang) {
        $this->datatables->select("a.id_perusahaan as id_perusahaan,a.nilai as nilai,b.nama as nama,IF(c.spesifikasi<d.spek_item or c.estimasi>d.est_item or c.tkdn<d.tkdn_item, 'Tidak Sesuai Permintaan', 'Sesuai Permintaan') as status");
        $this->datatables->from('nilai a, perusahaan b,barang c,pengumuman d');
        //add this line for join
        $this->datatables->where("a.id_perusahaan = b.id_perusahaan and c.id_perusahaan=b.id_perusahaan and c.jenis_lelang=d.jenis_lelang and d.jenis_lelang='$jenis_lelang'");
        //$this->datatables->add_column('action', anchor(site_url('nilai/read/$1'),'Read')." | ".anchor(site_url('nilai/update/$1'),'Update')." | ".anchor(site_url('nilai/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_perusahaan');
        return $this->datatables->generate();
    }
    // datatables,
    function jsonn() {
        $this->datatables->select("a.id_perusahaan as id_perusahaan,a.nilai as nilai,b.nama as nama,IF(c.spesifikasi<d.spek_item or c.estimasi>d.est_item or c.tkdn<d.tkdn_item, 'Tidak Sesuai Permintaan', 'Sesuai Permintaan') as status");
        $this->datatables->from('nilai a, perusahaan b,barang c,pengumuman d');
        //add this line for join
        $this->datatables->where("a.id_perusahaan = b.id_perusahaan and c.id_perusahaan=b.id_perusahaan and c.jenis_lelang=d.jenis_lelang");
        //$this->datatables->add_column('action', anchor(site_url('nilai/read/$1'),'Read')." | ".anchor(site_url('nilai/update/$1'),'Update')." | ".anchor(site_url('nilai/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_perusahaan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_perusahaan', $q);
	$this->db->or_like('nilai', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_perusahaan', $q);
	$this->db->or_like('nilai', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Nilai_model.php */
/* Location: ./application/models/Nilai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-27 13:32:03 */
/* http://harviacode.com */