<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengumuman_model extends CI_Model
{

    public $table = 'pengumuman';
    public $id = 'id_pengumuman';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pengumuman,id_user,jenis_lelang,judul_pengumuman,isi_pengumuman,tanggal,spek_item,est_item,tkdn_item');
        $this->datatables->from('pengumuman');
        //add this line for join
        //$this->datatables->join('table2', 'pengumuman.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pengumuman/read/$1'),'Lihat'),'id_pengumuman');
        return $this->datatables->generate();
    }

    function json2() {
        $this->datatables->select('id_pengumuman,id_user,jenis_lelang,judul_pengumuman,isi_pengumuman,tanggal,spek_item,est_item,tkdn_item');
        $this->datatables->from('pengumuman');
        //add this line for join
        //$this->datatables->join('table2', 'barang.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pengumuman/read/$1'),'Lihat')." | ".anchor(site_url('pengumuman/update/$1'),'Ubah')." | ".anchor(site_url('pengumuman/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pengumuman');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pengumuman', $q);
	$this->db->or_like('id_user', $q);
    $this->db->or_like('jenis_lelang', $q);
    $this->db->or_like('judul_pengumuman', $q);
	$this->db->or_like('isi_pengumuman', $q);
    $this->db->or_like('tanggal', $q);
    $this->db->or_like('spek_item', $q);
    $this->db->or_like('est_item', $q);
    $this->db->or_like('tkdn_item', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pengumuman', $q);
	$this->db->or_like('id_user', $q);
    $this->db->or_like('jenis_lelang', $q);
    $this->db->or_like('judul_pengumuman', $q);
	$this->db->or_like('isi_pengumuman', $q);
	$this->db->or_like('tanggal', $q);
    $this->db->or_like('spek_item', $q);
    $this->db->or_like('est_item', $q);
    $this->db->or_like('tkdn_item', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pengumuman_model.php */
/* Location: ./application/models/Pengumuman_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-10 15:08:45 */
/* http://harviacode.com */