<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Perusahaan_model extends CI_Model
{

    public $table = 'perusahaan';
    public $id = 'id_perusahaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_perusahaan,id_user,nama,alamat,status,keterangan');
        $this->datatables->from('perusahaan');
        //add this line for join
        //$this->datatables->join('table2', 'perusahaan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('perusahaan/read/$1'),'Lihat'),'id_perusahaan');
        return $this->datatables->generate();
    }

    function json2($id) {
        $this->datatables->select('id_perusahaan,id_user,nama,alamat,status,keterangan');
        $this->datatables->from('perusahaan');
        $this->datatables->where('id_user', $id);
        //add this line for join
        //$this->datatables->join('table2', 'barang.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('perusahaan/read/$1'),'Lihat')." | ".anchor(site_url('perusahaan/update/$1'),'Ubah'), 'id_perusahaan');
        return $this->datatables->generate();
    }

    function json3() {
        $this->datatables->select('id_perusahaan,id_user,nama,alamat,status,keterangan');
        $this->datatables->from('perusahaan');
        //add this line for join
        //$this->datatables->join('table2', 'barang.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('perusahaan/read/$1'),'Lihat')." | ".anchor(site_url('perusahaan/update/$1'),'Ubah')." | ".anchor(site_url('perusahaan/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_perusahaan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_nama($nama)
    {
        $this->db->where('nama', $nama);
        return $this->db->get($this->table)->row();
    }
    // get data by id
    function get_by_iduser($id)
    {
        $this->db->where('id_user', $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_perusahaan', $q);
    $this->db->or_like('id_user', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('alamat', $q);
    $this->db->or_like('status', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_perusahaan', $q);
    $this->db->or_like('id_user', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('alamat', $q);
    $this->db->or_like('status', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Perusahaan_model.php */
/* Location: ./application/models/Perusahaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-08 16:38:19 */
/* http://harviacode.com */